### ISSUE TITLE
How do I set an emoji?

### ISSUE THREAD

**Issue by ThomasBush** [codelittinc/slacked#13]
First of all thank you!  It was amazing to get slack integrated so quickly.  

I have tried setting an image/emoji in the actual slack api web interface for this particular web hook, but this doesn't seem to matter, I am still served the standard 'bot' icon inside of the app.  

It would be nice if I could choose the icon for my posts to slack, especially if I could associate different icons for different actions etc.  Is this possible through your gem?  Sorry if I am missing something obvious here.  Thanks!

**Comment by kaiomagalhaes** [comment]
Hy @ThomasBush, right now it is not possible to setup an emoji but it is a really good thing to do. I will work on it as soon as possible.

Can you give me examples of "associate different icons for different actions" because right now we only have the post action, maybe we could pass the icon when we send the message, would it resolve your problem?

Let me know and I will take a look on it.

**Comment by ThomasBush** [comment]
That would be awesome.  Sorry I worded that poorly.  I would just like the ability to set the emoji on each post if possible.  Currently I am only posting on a few `after_create` and `after_update` hooks, but it would be cool to post in other scenarios, I could see this being used to push errors, or maybe capistrano deploys etc.  So it would be nice to visually change the push as well.  So if there was a default emoji on the config and then the ability to override this in a post it would be really cool.

**Comment by codelitt** [comment]
So @ThomasBush basically just an additional argument for the method besides the `message` string?

**Comment by ThomasBush** [comment]
yup!

**Comment by kaiomagalhaes** [comment]
@ThomasBush @codelitt I will handle it by tomorrow probably and I let you know @ThomasBush

**Comment by codelitt** [comment]
@ThomasBush Implemented in https://github.com/codelittinc/slacked/issues/16

Closing issue.
