### ISSUE TITLE
Update gemspec

### ISSUE THREAD

**Issue by codelitt** [codelittinc/slacked#7]
Authors, summary and description. 

For summary maybe: 

>A super simple and easy way to send notifications to Slack from your Rails application. 

Description?? I'm not sure. Maybe: 

>This is a super simple Slack integration for Rails. A use case for this would be to post a notification in Slack when a new User is created or a certain action has been taken in your application. 

>Are there other gems that provide similar functionality? Yes. Do some of them provide more flexibility? Yes. The point of this was to make installing and integrating a 30 second process.

**Comment by kaiomagalhaes** [comment]
https://github.com/codelittinc/slacked/pull/9
